# Generated by Django 3.0.3 on 2020-07-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemssproj', '0002_auto_20200721_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
